---

# Format Ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# Required to un-FUBAR default ${{github.workflow}} value
name: check_cirrus_cron

on:
    schedule:
        # Assume test cirrus cron job runs every 15 minuntes
        - cron:  '*/20 * * * *'
    # Debug: trigger job manually in WebUI
    workflow_dispatch: {}

env:
    # Debug-mode can reveil secrets, only enable by a secret
    # Ref: https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging
    ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'
    # URL With CSV listing of zero or more e-mail addresses
    FAILMAILGIST: 'https://gist.githubusercontent.com/cevich/1e479c6811dc5b44508c2ba4dc295ff1/raw/csv'

jobs:
    cron_failures:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  persist-credentials: false

            - name: Get failed cron names and Build IDs
              id: cron
              run: './.github/actions/${{ github.workflow }}/${{ github.job }}.sh'

            - if: steps.cron.outputs.failures > 0
              shell: bash
              run: |
                set -eo pipefail
                while read -r NAME BID; do
                    echo "Cron build '$NAME' Failed: https://cirrus-ci.com/build/$BID"
                done < ./artifacts/name_id.csv > ./artifacts/email_body.txt

            - if: steps.cron.outputs.failures > 0
              id: mailto
              run: printf "::set-output name=csv::%s\n" $(curl --silent --location --url "$FAILMAILGIST")

            - if: steps.cron.outputs.failures > 0 && steps.mailto.outputs.csv != ''
              name: Send failure notification e-mail
              # Ref: https://github.com/dawidd6/action-send-mail
              uses: dawidd6/action-send-mail@v2.2.2
              with:
                server_address: ${{secrets.ACTION_MAIL_SERVER}}
                server_port: 465
                username: ${{secrets.ACTION_MAIL_USERNAME}}
                password: ${{secrets.ACTION_MAIL_PASSWORD}}
                subject: Cirrus-CI cron build failures on ${{github.repository}}
                to: ${{steps.mailto.outputs.csv}}
                from: ${{secrets.ACTION_MAIL_SENDER}}
                body: file://./artifacts/email_body.txt

            - if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}_artifacts
                  path: artifacts/*
